# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
  - master

jobs:
- job: builjob
  displayName: buildandpackage
  pool: 
    vmimage: ubuntu-22.04
  steps: 
    - task: DotNetCoreCLI@2
      inputs: 
        command: build
        projects: '**/NopCommerce.sln'
        arguments: '--configiration Release'
    - task: PowerShell@2
      inputs:
        targetType: 'inline'
        script: |
          # Write your PowerShell commands here.
          
          Write-Host "Hello World"
          Write-Host "I want to create build and release pipeline"
